version: '3.8'

services:
  gilgamesh:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8500:8500"
    volumes:
      - type: bind
        source: ${PWD}/app
        target: /app/app
        consistency: delegated
      - type: bind
        source: ${PWD}/tests
        target: /app/tests
        consistency: delegated
      - type: volume
        source: gilgamesh_cache
        target: /app/cache
    environment:
      - ENVIRONMENT=development
      - MAX_CONCURRENT_REQUESTS=5
      - REQUEST_TIMEOUT_SECONDS=300
      - CACHE_TTL_HOURS=24
      - PYTHONUNBUFFERED=1  # Ensure Python output is sent straight to terminal
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8500 --reload --reload-dir /app/app
    # Add some resource limits to prevent container from consuming too much
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

volumes:
  gilgamesh_cache:  # Named volume for persistent cache storage 