name: Docker Staging Build & Push

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: lenniott
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image (Staging)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: lenniott/gilgamesh:staging
